
CREATE TABLE IF NOT EXISTS genres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(150) NOT NULL,
    description varchar(200),
    release_date date NOT NULL,
    duration int NOT NULL,
    rating_id BIGINT REFERENCES ratings (id)
);

CREATE TABLE IF NOT EXISTS film_genres (
    film_id BIGINT REFERENCES films (id) ON DELETE CASCADE,
    genre_id BIGINT REFERENCES genres (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar NOT NULL,
    login varchar(150) NOT NULL,
    name varchar(150),
    birthday date NOT NULL
);

CREATE TABLE IF NOT EXISTS friendships (
    user_id BIGINT REFERENCES users (id) ON DELETE CASCADE ,
    friend_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
    is_confirmed BOOLEAN
);

CREATE TABLE IF NOT EXISTS likes (
    film_id BIGINT REFERENCES  films (id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users (id) ON DELETE CASCADE
);